platform:
  
  additional_packages:
    - cert-manager-webhook-hetzner
    - crossplane
    - flagger
    - gitops-configurer
    - metrics-server
    - opentelemetry-operator
    - postgresql-operator
  
  ingress:
    domain: <your-domain> # e.g. example.com
    issuer:
      type: letsencrypt
      email: changeme@example.com # Email address for ACME registration and recovery contact

cert_manager:
  letsencrypt:
    include: true
    production: true
    email: changeme@example.com # Email address for ACME registration and recovery contact
    challenge:
      type: dns01
      dns_provider: hetzner
      secret:
        name: hetzner-dns
        key: api-token

contour:
  envoy:
    service:
      annotations:
        load-balancer.hetzner.cloud/location: nbg1 # change to your cluster location, if needed
        load-balancer.hetzner.cloud/name: kadras-platform-lb
        load-balancer.hetzner.cloud/use-private-ip: "true"
        load-balancer.hetzner.cloud/http-redirect-https: "true"

flagger:
  meshProvider: knative
  metricsServer: http://prometheus-prometheus.observability:9090
  serviceMonitor:
    enabled: true
    honorLabels: true

flux:
  optional_components:
    helm_controller: true

gitops_configurer:
  type: flux-kustomization
  git:
    url: https://github.com/ThomasVitale/kubecon-2026-gitops # you can change this to your own Git repository to store the GitOps configuration for your cluster
    path: clusters/platform

workspace_provisioner:
  namespaces:
    - name: apps
    - name: observability
