---
apiVersion: apps.kadras.io/v1alpha1
kind: StoryApp
metadata:
  name: story-app-2
  namespace: apps
spec:
  image: ghcr.io/thomasvitale/scaling-on-satisfaction:db5f61de20b01be1048d2043557d62d6ec88e724
  story:
    theme: CIRCUS
    variant: A
