---
apiVersion: apps.kadras.io/v1alpha1
kind: StoryApp
metadata:
  name: story-app-2
spec:
  image: ghcr.io/thomasvitale/scaling-on-satisfaction:4905c965185e0c82e9b8ace35bf084e68f87bc05
  story:
    theme: CIRCUS
    variant: A
